Add old mca data
cn/GB2260 pull request #35
Opened 2016-09-19 02:06 UTC by ftao

历史数据在一些情况是有用， 特别是涉及的数据使用行政区划代码是历史已经废弃的时候。 
比如我的情况是身份证号码的验证。

2016-09-19 02:57 UTC, tonyseek commented
awesome! 👍

2016-09-19 15:26 UTC, lepture requested changes

2016-09-19 15:26 UTC, lepture commented on sources.tsv
> +mca 201412	http://files2.mca.gov.cn/cws/201502/20150225163817214.html	mca
tab 不太一致

2016-09-19 16:05 UTC, ftao commented on sources.tsv
> +mca 201412	http://files2.mca.gov.cn/cws/201502/20150225163817214.html	mca
这个tab 问题，后面一个 commit 改过的。 
https://github.com/cn/GB2260/pull/35/commits/2c8ca45445db7d5dce2728567d90357abe93d356

2016-09-20 02:42 UTC, tonyseek approved these changes

2016-09-25 03:43 UTC, merged