Update sources.tsv
cn/GB2260 pull request #41
Opened 2017-04-20 06:55 UTC by tkisme

2017-04-20 07:00 UTC, tonyseek requested changes

2017-04-20 07:00 UTC, tonyseek commented on sources.tsv
> +mca 201612  http://www.mca.gov.cn/article/sj/tjbz/a/2016/201702/201702231133.html mca
need tabs instead

2017-04-20 09:33 UTC, tkisme commented
changed

2017-04-20 09:46 UTC, tonyseek approved these changes

2017-04-21 01:19 UTC, lepture requested changes

2017-04-21 01:19 UTC, lepture commented on sources.tsv
> +mca 	201612  http://www.mca.gov.cn/article/sj/tjbz/a/2016/201702/201702231133.html mca
Just tabs no space. There are still many spaces instead of tabs.

2017-04-21 01:31 UTC, lepture commented
@tkisme I've added it https://github.com/cn/GB2260/commit/faf1839b2aee2f003e78c3e5d6434fab37e9dd3b

The tsv format is using tabs as the separator. 

Check your file at:
https://github.com/tkisme/GB2260/blob/d4269921dc4b8ee42f643ab360fc9bbcaa5849b9/sources.tsv

It shows a error message from GitHub. The right format should display a table instead https://github.com/cn/GB2260/blob/develop/sources.tsv

2017-04-21 01:31 UTC, closed without merging