新增stats文件 201810.tsv，新增mca文件 201904.tsv
cn/GB2260 pull request #51
Opened 2019-05-30 13:52 UTC by hugg95

1. 新增最新行政区划代码stats文件 `stats/201810.tsv`，[2018年统计用区划代码和城乡划分代码(截止2018年10月31日)](http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2018/index.html)
2. 新增mca文件 `mca/201904.tsv`，[2019年4月中华人民共和国县以上行政区划代码](http://www.mca.gov.cn/article/sj/xzqh/2019/201901-06/201905271445.html)

2019-05-31 06:27 UTC, tonyseek requested changes
Thank you for your contribution.

Please squash your commits and refine the commit messages.

2019-05-31 07:38 UTC, hugg95 commented
> Thank you for your contribution.
> 
> Please squash your commits and refine the commit messages.

I have refined my commits

2019-05-31 08:13 UTC, tonyseek commented
Hi @hugg95,

You could try to use `git pull --rebase upstream develop` instead of `git pull` directly or any other commands which imply `git merge`. It gives us a straight commit history. 

The `git config user.name <YOUR-NAME>` could be used for avoiding `commit author: unknown` also.

And then, I will checkout this pull request to local for checking the generated data.

Thank you!

2019-05-31 08:18 UTC, hugg95 commented
> Hi @hugg95,
> 
> You could try to use `git pull --rebase upstream develop` instead of `git pull` directly or any other commands which imply `git merge`. It gives us a straight commit history.
> 
> The `git config user.name <YOUR-NAME>` could be used for avoiding `commit author: unknown` also.
> 
> And then, I will checkout this pull request to local for checking the generated data.
> 
> Thank you!

Thanks, got it.

2019-05-31 09:02 UTC, tonyseek approved these changes
Looks good for me. Thanks again for your contribution!

2019-05-31 10:02 UTC, tonyseek commented on sources.tsv
> +stats	201810	http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2018/index.html	stats
It seems this URL could not be parsed by our script?

2019-05-31 10:09 UTC, hugg95 commented on sources.tsv
> +stats	201810	http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2018/index.html	stats
It seems that the government no longer provide these stats data in old way and old format, I wrote a script myself crawling these stats data from this URL.

2019-05-31 10:11 UTC, hugg95 commented on sources.tsv
> +stats	201810	http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2018/index.html	stats
We cannot access the URL "http://www.stats.gov.cn/tjsj/tjbz/xzqhdm/" now

2019-05-31 10:18 UTC, tonyseek commented on sources.tsv
> +stats	201810	http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2018/index.html	stats
Hmm... The National Bureau of Statistics removed the legacy pages and provided a layered one, which is more detailed (night-digits) but not compatible with the old one. :cry:

@lepture @timothyqiu, may we put the layered data into a new schema (e.g. `stats-v2`)?

@hugg95, would you merge your script into the `scripts/parser.py`?

2019-05-31 10:29 UTC, hugg95 commented on sources.tsv
> +stats	201810	http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2018/index.html	stats
No problem, but I need time to update the script because its not designed for reuse...

2019-05-31 11:30 UTC, timothyqiu commented on sources.tsv
> +stats	201810	http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2018/index.html	stats
@tonyseek @lepture The nine-digit code has being around for quite a long time. As the name suggests, it's the division code for statistical use (统计用区划和城乡划分代码), which is different from administrative division code (行政区划代码). The [Internet Archive page](https://web.archive.org/web/20180106161920/http://www.stats.gov.cn/tjsj/tjbz/xzqhdm/) shows that they were two different standards listed under two different sections of the website. 

So I believe it's not the National Bureau of Statistics replacing the legacy pages with more detailed ones. The Bureau is just quitting their role as a publisher of GB/T2260-compatible administrative division codes.

I think it's better to treat `stats` as a legacy data source which won't be updated any more. Then `mca` would be the only authoritative source of truth.

Anyway, GB/T2260 is, by definition, a six-digit code for divisions that are county level and above. Even if we decide to adopt the nine-digit source, divisions below county level should be dropped and the code should be truncated to conform to the standard.

Or maybe the nine-digit code should be a different feature / repository?

2019-05-31 11:35 UTC, tonyseek commented on sources.tsv
> +stats	201810	http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2018/index.html	stats
@timothyqiu Got it. Then we just need to update the parser and archive old data (or use https://archive.org as well).

2019-05-31 18:06 UTC, hugg95 commented on sources.tsv
> +stats	201810	http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2018/index.html	stats
@tonyseek  May I submit a new parser script in this pull-request?

2019-06-01 11:22 UTC, hugg95 commented on sources.tsv
> +stats	201810	http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2018/index.html	stats
@lepture @timothyqiu  If there is no problem with the new data files, colud you please promote theis pull request to be merged?
Thank you.

2019-06-03 10:42 UTC, hugg95 commented on sources.tsv
> +stats	201810	http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2018/index.html	stats
@tonyseek @lepture @timothyqiu
Could you please help me to update to the latest GB2260 data? Now we have a web system that running on production environment using these data.
Thank you!

2019-06-07 04:57 UTC, lepture approved these changes
LGTM

2019-06-07 04:57 UTC, merged

2019-06-07 04:58 UTC, lepture commented
@hugg95 Could you send another PR for `scripts/parser.py`?

2019-06-10 03:15 UTC, hugg95 commented
> @hugg95 Could you send another PR for `scripts/parser.py`?

I created a new [pull request](https://github.com/cn/GB2260/pull/52) for this script.

Just for your information, thanks!